### ISSUE TITLE
'Placeholder' is not assignable to parameter of type 'string | ((match: string, ...args: readonly any[]) => string)' in replace

### ISSUE THREAD

**Issue by shamshiyevulugbek** [ramda/types#109]
const greet = R.replace('{name}', R.__, 'Hello, {name}!');
greet('Alice'); //=> 'Hello, Alice!'

This is example in docs

**Comment by Harris-Miller** [comment]
It's a typescript issue. Not all functions are correctly typed to support currying and placeholders. It's been like that since we migrated the community-defined and supported types from `@types/ramda` over to here

`R.replace` is one example where it's typed for general currying, but not for use with the placeholder, and that needs to get fixed

@shamshiyevulugbek I'll try and get this looked at later this week
```
